# Generated by Django 5.1.2 on 2024-10-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_remove_ledgeraccount_cr_remove_ledgeraccount_dr'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionentry',
            name='title',
            field=models.CharField(default=5793286, max_length=255),
            preserve_default=False,
        ),
    ]
